### ISSUE TITLE
Exporting data with multi select option sets

### ISSUE THREAD

**Issue by halljames** [lucasalexander/AlexanderDevelopment.ConfigDataMover#12]
When exporting data that contains an attribute that is a Multi Select Option set, the GUI tool crashes with the following error.  Removing the MultiSelect OptionSet attribute enables the data to be exported correctly.

System.NullReferenceException: Object reference not set to an instance of an object.
   at AlexanderDevelopment.ConfigDataMover.Lib.Importer.TransformEntityList(List`1 entitylist) in C:\git-repos\AlexanderDevelopment.ConfigDataMover\AlexanderDevelopment.ConfigDataMover.Lib\Importer.cs:line 1207
   at AlexanderDevelopment.ConfigDataMover.Lib.Importer.Process() in C:\git-repos\AlexanderDevelopment.ConfigDataMover\AlexanderDevelopment.ConfigDataMover.Lib\Importer.cs:line 1024
   at AlexanderDevelopment.ConfigDataMover.Wpf.MainWindow.WorkerDoWork(Object sender, DoWorkEventArgs e) in C:\git-repos\AlexanderDevelopment.ConfigDataMover\AlexanderDevelopment.ConfigDataMover.Wpf\MainWindow.xaml.cs:line 338
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

**Comment by halljames** [comment]
Actually, I have just downloaded the Source Code, and ran the very latest version, and it worked fine, so I am guessing the latest actual release has this problem, but it has since been fixed.
